package ru.kolco24.kolco24.data.crypto

import kotlinx.serialization.json.Json
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Ignore
import org.junit.Test

/**
 * Server-vector verification for [LegendCrypto]. Unlike [LegendCryptoSanityTest] (which seals data
 * locally and only proves the AES-GCM wiring round-trips), these assertions pin the engine against a
 * vector generated by the server reference (`src/apps/mobile/crypto.py` + `legend_crypto.py`) — the
 * only thing that proves HKDF (`salt=None`→32 zero bytes), `bid`, and AAD interop byte-for-byte.
 *
 * ⚠️ GATED: the server vector is a blocking external artifact (see the plan's Prerequisite). Until it
 * lands, the vector constants below are PLACEHOLDERS and the vector assertions are [@Ignore]d so the
 * suite stays green without silently passing on fake data. The two vector-independent assertions
 * (tampered `ct` → [UnlockResult.Failed], open-CP tag → [UnlockResult.IdentityOnly]) run for real.
 *
 * TODO(server-vector): replace the placeholder constants with the real fixture, then remove every
 * `@Ignore` on the vector tests below and confirm green. Needed fixture:
 *  - [CODE_HEX]              — 16-byte NFC `code` (hex)
 *  - [EXPECTED_BID]          — `sha256(code).hex()[:16]`
 *  - [EXPECTED_WRAP_KEY_HEX] — `HKDF-SHA256(code, salt=None, info="kp-wrap-v1", len=32)` (hex)
 *  - [TAG_IV_B64]/[TAG_CT_B64] — the `bundle_blob` envelope for that `code`
 *  - [CP_ID] + [CP_ENC_IV_B64]/[CP_ENC_CT_B64] — a locked CP that tag opens
 *  - [EXPECTED_COST]/[EXPECTED_DESCRIPTION] — that CP's decrypted plaintext
 *  - ideally a second CP reached through the `content_key` indirection to cover the full chain
 */
class LegendCryptoTest {

    private val json = Json { ignoreUnknownKeys = true }

    // region ───────── PLACEHOLDER server vector (replace when the fixture lands) ─────────
    private companion object {
        // TODO(server-vector): real 16-byte code (hex).
        const val CODE_HEX = "00112233445566778899aabbccddeeff"

        // TODO(server-vector): sha256(code).hex()[:16].
        const val EXPECTED_BID = "0000000000000000"

        // TODO(server-vector): HKDF-SHA256(code, info="kp-wrap-v1", len=32), hex.
        const val EXPECTED_WRAP_KEY_HEX =
            "0000000000000000000000000000000000000000000000000000000000000000"

        // TODO(server-vector): bundle_blob envelope for CODE_HEX (Base64).
        const val TAG_IV_B64 = "AAAAAAAAAAAAAAAA"
        const val TAG_CT_B64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"

        // TODO(server-vector): a locked CP the tag opens + its enc envelope (Base64).
        const val CP_ID = 103
        const val CP_ENC_IV_B64 = "AAAAAAAAAAAAAAAA"
        const val CP_ENC_CT_B64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"

        // TODO(server-vector): that CP's decrypted plaintext.
        const val EXPECTED_COST = 5
        const val EXPECTED_DESCRIPTION = "Вершина"
    }
    // endregion

    private fun hex(s: String): ByteArray =
        ByteArray(s.length / 2) { s.substring(it * 2, it * 2 + 2).toInt(16).toByte() }

    private val code: ByteArray get() = hex(CODE_HEX)

    @Ignore("GATED on the server crypto vector — see Prerequisite / TODO(server-vector).")
    @Test
    fun bidMatchesServerVector() {
        assertEquals(EXPECTED_BID, LegendCrypto.bid(code))
    }

    @Ignore("GATED on the server crypto vector — see Prerequisite / TODO(server-vector).")
    @Test
    fun deriveWrapKeyMatchesServerVector() {
        assertArrayEquals(hex(EXPECTED_WRAP_KEY_HEX), LegendCrypto.deriveWrapKey(code))
    }

    @Ignore("GATED on the server crypto vector — see Prerequisite / TODO(server-vector).")
    @Test
    fun openDecryptsTagBundleToContentKeyMap() {
        val wrapKey = LegendCrypto.deriveWrapKey(code)
        val bid = LegendCrypto.bid(code)
        val bundleJson = String(
            LegendCrypto.open(wrapKey, TAG_IV_B64, TAG_CT_B64, bid.toByteArray(Charsets.US_ASCII)),
            Charsets.UTF_8,
        )
        // Expect a JSON object mapping the opened CP id → its Base64 content key.
        assertTrue(bundleJson.contains("\"$CP_ID\""))
    }

    @Ignore("GATED on the server crypto vector — see Prerequisite / TODO(server-vector).")
    @Test
    fun unlockRevealsCheckpointPlaintextFromVector() {
        val tag = UnlockTag(point = CP_ID, iv = TAG_IV_B64, ct = TAG_CT_B64)
        val result = LegendCrypto.unlock(
            code = code,
            tag = tag,
            encById = mapOf(CP_ID to EncBlob(iv = CP_ENC_IV_B64, ct = CP_ENC_CT_B64)),
            json = json,
        )
        assertTrue(result is UnlockResult.Revealed)
        val revealed = (result as UnlockResult.Revealed).checkpoints.single { it.id == CP_ID }
        assertEquals(EXPECTED_COST, revealed.cost)
        assertEquals(EXPECTED_DESCRIPTION, revealed.description)
    }

    // ───────── Vector-independent: these run for real (no server fixture needed). ─────────

    @Test
    fun unlockReturnsIdentityOnlyForOpenCpTag() {
        val result = LegendCrypto.unlock(
            code = ByteArray(16),
            tag = UnlockTag(point = 101, iv = null, ct = null),
            encById = emptyMap(),
            json = json,
        )
        assertEquals(UnlockResult.IdentityOnly(101), result)
    }

    @Test
    fun unlockFailsOnTamperedCiphertext() {
        // No server vector required: any malformed envelope fails the GCM tag check → Failed.
        val tag = UnlockTag(point = CP_ID, iv = TAG_IV_B64, ct = TAG_CT_B64)
        val result = LegendCrypto.unlock(
            code = code,
            tag = tag,
            encById = emptyMap(),
            json = json,
        )
        assertTrue(result is UnlockResult.Failed)
    }
}
