package ru.kolco24.kolco24.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — seed color #B3261E (brand red)
val md_light_primary = Color(0xFFB3261E)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFFDAD5)
val md_light_onPrimaryContainer = Color(0xFF410002)
val md_light_secondary = Color(0xFF775652)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFFFDAD6)
val md_light_onSecondaryContainer = Color(0xFF2C1513)
val md_light_tertiary = Color(0xFF1F7A3D)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_tertiaryContainer = Color(0xFFA6F2BC)
val md_light_onTertiaryContainer = Color(0xFF002109)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFFFBFF)
val md_light_onBackground = Color(0xFF201A19)
val md_light_surface = Color(0xFFFFFBFF)
val md_light_onSurface = Color(0xFF201A19)
val md_light_surfaceVariant = Color(0xFFF5DDDA)
val md_light_onSurfaceVariant = Color(0xFF534341)
val md_light_outline = Color(0xFF857370)
val md_light_outlineVariant = Color(0xFFD8C2BE)
val md_light_inverseSurface = Color(0xFF362F2E)
val md_light_inverseOnSurface = Color(0xFFFBEEEB)
val md_light_inversePrimary = Color(0xFFFFB4AB)
val md_light_surfaceContainer = Color(0xFFF4E7E4)

// Dark theme
val md_dark_primary = Color(0xFFFFB4AB)
val md_dark_onPrimary = Color(0xFF690003)
val md_dark_primaryContainer = Color(0xFF930009)
val md_dark_onPrimaryContainer = Color(0xFFFFDAD5)
val md_dark_secondary = Color(0xFFE7BDBA)
val md_dark_onSecondary = Color(0xFF442928)
val md_dark_secondaryContainer = Color(0xFF5D3F3C)
val md_dark_onSecondaryContainer = Color(0xFFFFDAD6)
val md_dark_tertiary = Color(0xFF5DDF82)
val md_dark_onTertiary = Color(0xFF003919)
val md_dark_tertiaryContainer = Color(0xFF00391C)
val md_dark_onTertiaryContainer = Color(0xFF7AF89A)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690003)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF201A19)
val md_dark_onBackground = Color(0xFFEDE0DD)
val md_dark_surface = Color(0xFF201A19)
val md_dark_onSurface = Color(0xFFEDE0DD)
val md_dark_surfaceVariant = Color(0xFF534341)
val md_dark_onSurfaceVariant = Color(0xFFD8C2BE)
val md_dark_outline = Color(0xFFA08C8A)
val md_dark_outlineVariant = Color(0xFF534341)
val md_dark_inverseSurface = Color(0xFFEDE0DD)
val md_dark_inverseOnSurface = Color(0xFF362F2E)
val md_dark_inversePrimary = Color(0xFFB3261E)
val md_dark_surfaceContainer = Color(0xFF2E2422)
